version: 0.2

phases:
  pre_build:
    commands:
      - echo "we are in pre-build phase"
  build :
    commands:
      - echo "we are in build phase"
      - grep -Fq "aruna" index.html
  post_build:
    commands:
      - echo "we are in post-build stage"
      