version: 0.2

phases:
  pre_build:
    commands:
      - echo "We are in the pre-build phase"
  build:
    commands:
      - echo "We are in the build phase"
  post_build:
    commands:
      - echo "Checking for the string 'aruna' in index.html"
      - grep -qi "aruna" index.html || { echo "String 'aruna' not found. Failing the build."; exit 1; }
      - echo "String 'aruna' found. Proceeding with the post-build phase."

artifacts:
  files:
    - '**/*'
  name: portfolio-$(date +%Y-%m-%d) 

